[tool.poetry]
name = "quantumco"
version = "0.0.0"
description = "PortFolio"
authors = ["Kamyar Bashar"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
